### PR TITLE
ci update

### PR DESCRIPTION
**Pull request by tomerd**
motivation: 5.6 is out

changes:
* use missing ci for 5.4, 5.5 and 5.6
* add docker setup for 5.7 (using nightly for now) and nightly

### CODE REVIEW

**Review by ktoso — APPROVED** [review]
Nice, thank you!

**Comment by ktoso** [comment]
gotta love `gem` 
```
02:38:13 ERROR:  While executing gem ... (OptionParser::InvalidOption)
02:38:13     invalid option: --no-ri
```

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by ktoso** [comment]
Sweet, thanks 👍

**Pull request merged**
